name: Robot Tests CD

on:
  workflow_dispatch:
    inputs:
      teste_scenario:
        type: choice
        description: 'Teste scenario'
        options: 
        - add_to_cart
        - search_error
        - all_tests       

jobs:
  run_testes:
    name: Run Robot tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.2'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt
    
    - name: Select version
      id: update_tag
      run: |
        if [[ "${{ github.event.inputs.teste_scenario }}" == "all_tests" ]]; then
          updated_tag="${{matrix.tags}} and @SANITY"
        else
          updated_tag="${{matrix.tags}}"
        fi
        echo "new_tag=$updated_tag" >> $GITHUB_OUTPUT

    - name: Run tests
      run: |
        if [[ "${{ github.event.inputs.teste_scenario }}" == "all_tests" ]]; then
          robot scenarios/**.robot
        else
          robot scenarios/${{ github.event.inputs.teste_scenario }}.robot
        fi
        
    
    - name: Storage Robot Report
      uses: actions/upload-artifact@v3
      with: 
        name: Robot_report
        path: report.html
    
    - name: Move report files
      run: |
        mkdir ./html
        mv report.html ./html
    
    - name: Publish Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        destination_dir: ./
